### ISSUE TITLE
Node down with a error - Insufficient resources: could not allocate code memory: Cannot allocate memory (os error 12)

### ISSUE THREAD

**Issue by SNSMLN** [near/stakewars-iv#61] opened 2024-03-11 16:52 UTC
My node went down for no reason. In the neard log there is only this

```
Mar 11 16:57:50 node01new neard[882540]: 2024-03-11T15:57:50.306463Z  INFO stats: #033[1;49;33m#114493881 DnowrgBqgcK4Wo5CGufbhQbX4BpNeT4hGiw1q6a1FkbH#0
33[0m#033[1;49;37m Validator | 20 validators#033[0m#033[1;49;36m 43 peers ⬇ 19.3 MB/s ⬆ 48.3 MB/s#033[0m#033[1;49;32m 1.00 bps 36.9 Tgas/s#033[0m#033[1;
49;34m CPU: 300%, Mem: 3.79 GB#033[0m                                                                                                                   
Mar 11 16:57:54 node01new neard[882540]: 2024-03-11T15:57:54.167114Z  INFO near_network::peer_manager::connection: peer ed25519:2SVMYgTYcEgnxYGyr9XxHUZF
Hf7XfS43DaHNAHnFwgpw disconnected, while sending SyncAccountsData                                                                                       
Mar 11 16:57:54 node01new neard[882540]: 2024-03-11T15:57:54.167128Z  INFO near_network::peer_manager::connection: peer ed25519:2SVMYgTYcEgnxYGyr9XxHUZF
Hf7XfS43DaHNAHnFwgpw disconnected, while sending SyncAccountsData                                                                                       
Mar 11 16:57:55 node01new neard[882540]: thread '<unnamed>' panicked at runtime/runtime/src/actions.rs:172:13:                                          
Mar 11 16:57:55 node01new neard[882540]: Contract runtime failed to load a contrct: Insufficient resources: could not allocate code memory: Cannot alloc
ate memory (os error 12)                                                                                                                                
Mar 11 16:57:55 node01new neard[882540]: stack backtrace:                                                                                               
Mar 11 16:57:55 node01new neard[882540]: thread '<unnamed>' panicked at runtime/runtime/src/actions.rs:172:13:                                          
Mar 11 16:57:55 node01new neard[882540]: Contract runtime failed to load a contrct: Insufficient resources: could not allocate code memory: Cannot alloc
ate memory (os error 12)                                                                                                                                
Mar 11 16:57:55 node01new neard[882540]:    0: rust_begin_unwind                                                                                        
Mar 11 16:57:55 node01new neard[882540]:              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5             
Mar 11 16:57:55 node01new neard[882540]:    1: core::panicking::panic_fmt                                                                               
Mar 11 16:57:55 node01new neard[882540]:              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14            
Mar 11 16:57:55 node01new neard[882540]:    2: node_runtime::actions::execute_function_call                                                             
Mar 11 16:57:55 node01new neard[882540]:    3: node_runtime::Runtime::apply_action                                                                      
Mar 11 16:57:55 node01new neard[882540]:    4: node_runtime::Runtime::apply_action_receipt                                                              
Mar 11 16:57:55 node01new neard[882540]:    5: node_runtime::Runtime::apply::{{closure}}                                                                
Mar 11 16:57:55 node01new neard[882540]:    6: node_runtime::Runtime::apply                                                                             
Mar 11 16:57:55 node01new neard[882540]:    7: <nearcore::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::apply_chunk                 
Mar 11 16:57:55 node01new neard[882540]:    8: near_chain::update_shard::apply_new_chunk                                                                
Mar 11 16:57:55 node01new neard[882540]:    9: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute                                        
Mar 11 16:57:55 node01new neard[882540]:   10: rayon_core::registry::WorkerThread::wait_until_cold                                                      
Mar 11 16:57:55 node01new neard[882540]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.                        
Mar 11 16:57:55 node01new neard[882540]: stack backtrace:                                                                                               
Mar 11 16:57:55 node01new neard[882540]:    0: rust_begin_unwind                                                                                        
Mar 11 16:57:56 node01new neard[882540]:              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
```

In syslog :

```
Mar 11 16:57:56 node01new systemd[1]: neard.service: Main process exited, code=killed, status=6/ABRT                                                    
Mar 11 16:57:56 node01new systemd[1]: neard.service: Failed with result 'signal'.                                                                       
Mar 11 16:58:26 node01new systemd[1]: neard.service: Scheduled restart job, restart counter is at 1.                                                    
Mar 11 16:58:26 node01new systemd[1]: Stopped Near node.                                                                                                
```

Grafana is installed on the server. There's also nothing that attracts attention.

![Screenshot_2024-03-11_19-36-08](https://github.com/near/stakewars-iv/assets/76874974/947ad15b-a4e8-4e87-8708-b208d4ed8892)
![Screenshot_2024-03-11_19-35-47](https://github.com/near/stakewars-iv/assets/76874974/cd1a4ac5-7c2d-4fe6-95ab-c3c9b163033d)
![Screenshot_2024-03-11_19-37-04](https://github.com/near/stakewars-iv/assets/76874974/b4740bbe-9327-42e3-acbe-e661da743841)
![Screenshot_2024-03-11_19-37-19](https://github.com/near/stakewars-iv/assets/76874974/01bf26f5-dd76-46d1-8a73-06269bada987)
![Screenshot_2024-03-11_19-37-35](https://github.com/near/stakewars-iv/assets/76874974/94182de6-04f0-49ab-b675-b6e24d77466c)
![Screenshot_2024-03-11_19-37-51](https://github.com/near/stakewars-iv/assets/76874974/0bcc2469-b91a-4d82-b6ff-ec17d5ac7276)
![Screenshot_2024-03-11_19-38-08](https://github.com/near/stakewars-iv/assets/76874974/373d6c86-8619-4cc6-9e8d-bcd58e3860f7)

The only thing. Increased number of memory page faults
![Screenshot_2024-03-11_20-00-26](https://github.com/near/stakewars-iv/assets/76874974/530b70f2-1a98-4697-9537-8f58940f0df3)

**Comment by walnut-the-cat** [comment] 2024-03-11 20:34
cc. @alexauroradev @marcelo-gonzalez

**Comment by pugachAG** [comment] 2024-03-12 16:01
Looks like an issue due to insufficient memory, but "Memory Basic" dashboard seems to indicate that node still had enough memory. @nagisa this was originated from the runtime, maybe you know what could be the source of this?

**Comment by pugachAG** [comment] 2024-03-12 18:38
The issues should be fixed not with https://github.com/near/nearcore/pull/10733 and https://github.com/near/nearcore/pull/10736. So this should no longer happens after we release new neard version for statelessnet.

**Comment by walnut-the-cat** [comment] 2024-03-21 18:35
@DDeAlmeida  could you confirm if the issue is gone now?

**Comment by SNSMLN** [comment] 2024-03-22 05:17
> @SNSMLN , @DDeAlmeida could you confirm if the issue is gone now?

After updating to build 1.36.1-298-g984f6ad71 the issue no longer appeared

**Comment by DDeAlmeida** [comment] 2024-03-22 08:29
Same here

**Closed** 2024-03-22 15:00 UTC
